site/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Route::get('/','PageController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('articles','ArticleController');
//Route::get('articles/{id}/edit','ArticleController');
Route::post('comments/{article}' , 'CommentController@store')->name('comments.store');

site/resources/views/home.blade.php
@extends('layouts.app')
@section('title' , __('Home '))
@section('content')

<div class="container">
   <a href="{{route('articles.create')}}" class="btn btn-lg btn-outline-warning mt-4 mb-4">{{__('New article')}}</a>
</div>
<hr>
    <div class="row mt-4">
    @forelse($articles as $article)
        <div class="col-md-3">
            <div class="mb-2 card">
                <div class="card-body">
                    <a href="{{route('articles.show' , $article)}}">{{$article->title}}</a>
                </div>
                <div class="card-footer">
                    <a href="{{route('articles.edit' ,$article)}}" class="btn btn-outline-dark">{{__('Edit')}}</a>
                    <form  method="post" action="{{route('articles.destroy',$article)}}" style="display: inline-block">
                        @method('DELETE')
                        @csrf
                        <button class="btn btn-outline-danger" onclick="return confirm('{{__('Are you sure?')}}')">{{__('Delete')}}</button>
                    </form>
                </div>
            </div>
        </div>

    @empty
    {{__('sorry you done have any articles yet')}}
    @endforelse
    </div>
@endsection

site/resources/views/index.blade.php
@extends('layouts.app')
@section('title' , __('Home page'))

@section('content')

        <style>
            .jumbotron{
                background-image:url("{{ URL::asset('image/w6.jpg')}}") ;
                height: 600px;
                width: 1105px;
                opacity: 0.7;
            }
            div.transbox {
                margin:40px;
                background-color: #ffffff;
                border: 1px  ;
                opacity: 0.6;
            }
            div.transbox p {
                margin: 20%;
                font-weight: bold;
                font-family: 'hanimation';
                text-align: center;
                font-size:30px;
                color: #1f1c14;
            }

        </style>
       {{-- <h3>{{__('welcome to ')}} {{config('app.name')}}</h3>--}}
        <div class="jumbotron ">
            <div class="transbox">

                <p>حلم الأمس سيصبح حقيقية يوماً ما حارب لأجله.</p>
            </div>
        </div>
        <hr>
    <h3 class="text-warning">{{__('Latest articles ')}}</h3>
        <hr>
    <div class="row ">
        @forelse($articles as $article)

            @include('article._article_card')

        @empty
         {{__('No articles yet')}}
        @endforelse
    </div>
        <hr>
        <a class="btn btn-link-dark btn-outline-warning text-dark mb-2 pr-4" href="{{route('articles.index')}}"><b>{{__('Browse all article')}}</b></a>
        <hr>

@endsection