site/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Route::get('/','PageController@index')->name('index');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('articles','ArticleController');
//Route::get('articles/{id}/edit','ArticleController');
Route::post('comments/{article}' , 'CommentController@store')->name('comments.store');

site/app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
   use SoftDeletes;
   protected $fillable =[
     'title',
     'user_id',
     'content'
   ];
   protected $dates=['delete_at'];
   public function user(){
       return $this->belongsTo(User::class);
   }

       public function categories()
       {
           return $this->belongsToMany(Category::class ,'add_article_category',
               'article_id',
               'category_id');

       }

    public function comments(){
        return $this->hasMany(Comment::class );
    }



}

site/app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class ArticleController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except('show');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $articles=Article::orderBy('id','DESC')->get();
        return view('article.index' ,compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       $categories=Category::all()->pluck('title','id');
       // dd($categories);
        return view('article.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)

    {
        $request->validate([
            'title'=>'max:50|min:5|required',
            'content'=>'min:50|required',
            'categories'=>'required'

        ]);
       // dd($request->categories);
        //save data

       $user=Auth::user();
       //$categories=array_values($request->categories); //return array like this [1,2]
       // dd($categories);
         $data=$user->articles()->create($request->except('categories'));

      $article=Article::find($data->id);  //last article insert
      foreach ($request->categories as $category){
          $article->categories()->attach($category);
      }

     return redirect()->to('/home');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        //display article in the page
        return view('article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */


    public function edit(Article $article)
    {
        if(Auth::id() != $article->user_id){
            return abort(401);
        }
        $categories=Category::pluck('title','id');
        //view categories the user is choice
        $articleCategories=$article->categories()->pluck('id')->toArray();
        return view('article.edit',compact('categories' ,'article' ,'articleCategories'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        if(Auth::id() != $article->user_id){
            return abort(401);
        }

        $request->validate([
            'title'=>'max:50|min:20|required',
            'content'=>'min:140|required',
            'categories'=>'required'

        ]);
        //$article->title = $request['title'];
        //$article->content = $request['content'];
       // $article->save();
        //shortcut above
        $article->update($request->all());
       //يشيل التصنيف القديم اذ عدل ويحط الجديد
        $article->categories()->sync($request->categories);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        if(Auth::id() != $article->user_id){
            abort(401);
        }
     $article->delete();
     return redirect()->back();
    }
}

site/resources/views/article/_article_card.blade.php
<div class="col-md-4 mb-2">
    <div class="card pb-3">

        <h4 class="card-header" ><a class="text-secondary" href="{{route('articles.show', $article->id)}}">{{$article->title}}</a></h4>
        <div class="card-body">
            {{$article->content}}
        </div>

        <div class="card-footer">
            {{__('Author')}} : {{$article->user->name}}
        </div>
    </div>
</div>

site/resources/views/article/_form.blade.php
<div class="container">
@csrf
<div class="form-group">
    <label for="title">{{__('Title')}}</label>
    <input type="text" name="title" class="form-control" @isset($article) value="{{$article->title}}" @endisset>
</div>
    <div class="form-group">
        @foreach($categories as $id =>$title)
            <label for="category__{{$id}}">{{$title}}</label>
            <input type="checkbox" name="categories[]" value="{{$id}}" id="category__{{$id}}"

            @if(isset($article) && in_array($id ,$articleCategories)) checked @endif
            >
        @endforeach
    </div>

<div class="form-group">
    <label for="content">{{__('Content')}}</label>
    <textarea class="form-control" name="content" id="content" cols="20" rows="10" >@isset($article) {{$article->content}} @endisset</textarea>
</div>

<div class="form-group">
    <button class="btn btn-success">{{$submitText}}</button>
</div>
</div>

site/resources/views/article/create.blade.php
@extends('layouts.app')
@section('title' , __('Create article'))

@section('content')
    <h2>{{__('Create article')}}</h2>
    <form action="{{route('articles.store')}}" method="post">
      @include('article._form' ,['submitText' => __('Save')]  )
    </form>
@endsection

site/resources/views/article/edit.blade.php
@extends('layouts.app')
@section('title' , __('Edit article'))

@section('content')
    <h2>{{__('Edit article')}} : {{$article->title}}</h2>
    <form action="{{route('articles.update' , $article)}}" method="post">
        @method('PATCH  ')
        @include('article._form' , ['submitText' => __('Edit')])
    </form>
@endsection

site/resources/views/article/index.blade.php
@extends('layouts.app')
@section('title' , __('Create article'))

@section('content')

    <div class="row">
    @forelse($articles as $article)

         @include('article._article_card')

         @empty
            {{__('No articles yet')}}
    @endforelse
    </div>
@endsection

site/resources/views/article/show.blade.php
@extends('layouts.app')
@section('title' , $article->title)

@section('content')

    <div class="container ">
    <div class="card">
        <div class="card-header ">{{$article->title}}</div>


    <div class="card-body">
        {!!nl2br($article->content)!!}
    </div>
    {{--disply info about the author --}}
    <div class="card-footer">
        <div><b>{{__('Author')}} </b>: {{$article->user->name}}</div>
        <div><b>{{__('Created at')}}</b>: {{$article->created_at}}</div>
    </div>
    </div>
    {{--show comments under the article --}}
        <h3 class="mt-2 text-warning">{{__('Comments :')}}</h3>

     <div id="comments" class="mt-4 ">
         @forelse($article->comments as $comment)
          <div class="card p-3 mb-2">
              {{$comment->content}}
              <p>{{__('Author')}} : {{$comment->user->name}}</p>
          </div>
         @empty
         {{__('No comment yet')}}
         @endforelse
     </div>

     @auth
    <div id="commentForm " class="mt-5">
        <div class="card ">
            <h5 class="card-header bg-secondary text-white">{{__('Type your comment here')}}</h5>
            <div class="card-body">
                <form action="{{route('comments.store' ,$article->id)}}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="content">{{__('Content')}}</label>
                        <textarea class="form-control"
                                  placeholder="{{__('Type your comments')}}"
                                  name="content" id="content" cols="30" rows="10"></textarea>
                    </div>

                    <div class="form-group">
                        <button class="btn btn-outline-success" type="submit">{{__('Save')}}</button>
                    </div>

                </form>
            </div>
        </div>

    </div>
        @else
        <p><a href="{{route('login')}}"> {{__('Log in to comment')}}</a></p>
        @endauth
    </div>
@endsection